docs/docusaurus.config.js

chore: Changed the URL used for "Edit this page" links

---

docs/docs/components/icon.md
docs/docs/components/login.md
docs/docs/components/option-dialogs/confirm.md
docs/docs/components/splitter.md

This PR will close Issue #165.

chore: Corrected artifacts for Java API links

---

src/main/java/com/webforj/samples/views/googlecharts/ChartGalleryView.java

chore: Redirected links from webforj-docs-samples to webforj-documentation

---

docs/docs/building-ui/component-basics.md

chore: Corrected components inside `add()` method

---

pom.xml

This PR will close Issue #202.

chore: Replaced deprecated expressions

---

docs/docs/building-ui/component-basics.md
src/main/java/com/webforj/samples/components/CodeDisplay.java
src/main/java/com/webforj/samples/views/dialog/DialogAutoFocusView.java
src/main/java/com/webforj/samples/views/dialog/DialogPositioningView.java
src/main/java/com/webforj/samples/views/drawer/DrawerAutoFocusView.java

@see https://github.com/webforj/webforj/pull/929
closes #83

fix: replace deprecated code

---

src/main/java/com/webforj/samples/views/googlecharts/ChartRedrawView.java
src/main/resources/css/googlecharts/chartRedraw.css

fixes for #116 #118 #117 #114 
Added validation for numeric inputs in ChartRedraw, implemented a toast error message for invalid entries, and enabled scrolling to prevent content cutoff on smaller screens.

Chartredraw fixes

---

docs/docs/components/flex-layout.md
src/main/java/com/webforj/samples/views/flexlayout/FlexLayoutView.java

- compared to columnslayout
- fixes #113

Updated flex demo layout

---

docs/docs/components/fields/time-field.md

removing seconds tip

---

docs/docs/components/table/table_sorting.md
src/main/java/com/webforj/samples/views/table/TableMultiSortingView.java

- Updated table sorting documentation to clarify usage of setSortable and setMultiSorting
- Added new demo to showcase multi-column sorting
- Improved explanation of sorting behavior for better user guidance
- closes #220

Update sorting documentation and add demo for multi-column sorting

---

src/main/java/com/webforj/samples/views/button/ButtonView.java

Setting gap to var(--dwc-space-l) instead of px

---

docs/docs/configuration/bbj-installation/local.md

91- adding mac maven installation guide

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
CONTRIBUTING.md

Heavily utilized this template for flow and clarity:
https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md

feat: created contribution guide with templates for opening issues

---

docs/src/components/DocsTools/DocChip.js

This PR will close Issue #295.

refactor: Use relative URL instead of absolute for `DocChip`

---

docs/docs/client-components/toolbar.md
docs/docs/components/_dwc_control_map.json
docs/docs/components/app-layout.md
docs/docs/components/overview.md
docs/docs/components/toolbar.md
src/main/java/com/webforj/samples/views/toolbar/ToolbarCompactView.java
src/main/java/com/webforj/samples/views/toolbar/ToolbarProgressbarView.java
src/main/java/com/webforj/samples/views/toolbar/ToolbarSlotsView.java
src/main/java/com/webforj/samples/views/toolbar/ToolbarThemeView.java

This PR will close Issue #9 and Issue #19.

docs: Added `Toolbar` article and two demos

---

docs/docs/components/appnav.md

chore: Fixed URL for `AppNavView`

---

src/main/java/com/webforj/samples/views/elementcomposite/QRPropertiesView.java

This PR will close Issue #329.

chore: Corrected URL in `QRPropertiesView` sample

---

.github/.styles/config/vocabularies/webforj/accept.txt
.github/.styles/webforJ/Capitalization.yml
.vale.ini
docs/docs/introduction/getting-started.md

This PR will close Issue #323 by using the correct capitalization of startforJ and adds a style guide that will check for the correct capitalization of webforJ and startforJ for future development.

feat: Added capitalization styling for webforJ and startforJ

---

docs/docs/components/app-layout.md

The demos in the applayout were not showing the code properly as the links were not updated.

fixed demo links to show code properly.

---

docs/docs/components/table/table_sorting.md
src/main/java/com/webforj/samples/views/table/TableSortOrderView.java

feat: add to Table sorting doc table sort index

---

docs/docs/components/table/table_dynamic_styling.md
src/main/java/com/webforj/samples/views/table/TableLayoutStylingView.java

documenting table borders and striped rows
closes #235

feat:document table borders and striped rows

---

docs/docs/components/fields/date-time-field.md

https://github.com/webforj/webforj-documentation/issues/54
https://github.com/webforj/webforj-documentation/issues/55

DateTimeField enhancements.

---

docs/docs/components/fields/number-field.md

https://github.com/webforj/webforj-documentation/issues/52
https://github.com/webforj/webforj-documentation/issues/53

Numberfield enchancements.

---

src/main/java/com/webforj/samples/views/fields/timefield/TimeFieldView.java

This PR will close Issue #126.

chore: Removed unused class name in `TimeFieldView`

---

docs/docs/building-ui/component-basics.md
docs/docs/building-ui/elements.md

This PR will close Issue #394.

chore: Added JavaDoc links to `PendingResult`

---

docs/docs/introduction/getting-started.md

I've made some revisions to the Getting Started page to improve style and clarity, fix some errors, and expand on some of the information.

chore: make revisions to Getting Started.

---

docs/docs/components/app-layout.md

fix: Corrected URL for AppLayoutDrawerUtilityView.java

---

docs/blog/2025-07-15-webforj-v25.02/25.02.md

This PR will close Issue #424.

chore: 25.02 blog release date correction

---

docs/package-lock.json
docs/package.json
docs/src/css/_announcement.scss

Please check if anything obviously broken in our components after the upgrade,. I noticed that the announcement bar styling was broken, so I went ahead and fixed it.

chore: update Docusaurus to version 3.8.1

---

docs/docs/building-ui/archetypes/blank.md
docs/docs/building-ui/archetypes/hello-world.md
docs/docs/building-ui/archetypes/sidemenu.md
docs/docs/building-ui/archetypes/tabs.md

This PR will close Issue #435 by hiding the TOC in each of the archetype articles.

chore: Hide TOCs in archetypes

---

docs/docs/building-ui/archetypes/overview.md

This PR will close Issue #434.

chore: Remove comments from archetype overview

---

docs/docs/data-binding/validation/overview.md

This PR will close Issue #454.

fix: Made the validation overview article have only one `AskMenu`

---

docs/docs/configuration/overview.md

This PR will close Issue #437.

chore: Hide TOC in configuration overview

---

src/main/java/com/webforj/samples/views/drawer/DrawerContactView.java

This PR will close Issue #490.

fix: Used `StyleSheet` annotation for `DrawerContactView`

---

docs/docs/configuration/deploying-additional-servlets.md
docs/docusaurus.config.js

This PR will close Issue #477.

Moved "Deploying Additional Servlets" to the configuration section and added a redirect

---

docs/docs/integrations/spring/scopes.md

feat: add documentation for Spring scopes

---

docs/docs/routing/navigation-lifecycle/navigation-events.md
docs/docs/routing/navigation-lifecycle/observers.md
docs/docs/routing/navigation-lifecycle/overview.md

feat: document Router Activate lifecycle

---

docs/docs/advanced/asynchronous-updates.md
docs/docs/advanced/browser-console.md
docs/docs/advanced/browser-history.md
docs/docs/advanced/error-handling.md
docs/docs/advanced/interval.md
docs/docs/advanced/lifecycle-listeners.md
docs/docs/advanced/namespaces.md
docs/docs/advanced/object-string-tables.md
docs/docs/advanced/repository/_category_.json
docs/docs/advanced/terminate-and-error-actions.md
docs/docs/advanced/web-storage.md

This PR will close Issue #387.

Reordered the articles in the Advanced Topics section

---

docs/blog/authors.yml

This PR will close Issue #543.

chore: Added LinkedIn link for webforJ author

---

docs/docusaurus.config.js
docs/src/css/_navbar.scss
docs/static/js/style-startforj.js

This PR will close Issue #547.
https://github.com/user-attachments/assets/b076b2a1-f208-4f0b-8c73-4558c0358f20

feat: Added startforJ button

---

src/main/java/com/webforj/samples/views/table/TableColumnAutoSizingView.java

fix: fixed issue with reset to default not working

---

src/main/java/com/webforj/samples/views/terminal/TerminalView.java

Fixing issue where Terminal was processing commands incorrectly
closes #380

fix(terminal): use StringBuilder to handle backspace correctly
